export enum Icons {
  AppleLogo = 'apple-logo',
  CarbonAdd = 'carbon-add',
  CarbonApplication = 'carbon-application',
  CarbonArrowLeft = 'carbon-arrow-left',
  CarbonCaretDown = 'carbon-caret-down',
  CarbonChartMultitype = 'carbon-chart-multitype',
  CarbonCloseOutline = 'carbon-close-outline',
  CarbonColorPalette = 'carbon-color-palette',
  CarbonCompass = 'carbon-compass',
  CarbonEdit = 'carbon-edit',
  CarbonEmail = 'carbon-email',
  CarbonLogout = 'carbon-logout',
  CarbonMenu = 'carbon-menu',
  CarbonNotificationOff = 'carbon-notification-off',
  CarbonOverflowMenuHorizontal = 'carbon-overflow-menu-horizontal',
  CarbonOverflowMenuVertical = 'carbon-overflow-menu-vertical',
  CarbonRadioButton = 'carbon-radio-button',
  CarbonRadioButtonChecked = 'carbon-radio-button-checked',
  CarbonSettings = 'carbon-settings',
  CarbonTemplate = 'carbon-template',
  CarbonTrashCam = 'carbon-trash-can',
  CarbonUserAvatar = 'carbon-user-avatar',
  GoogleLogo = 'google-logo'
}
